//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Protal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_info
    {
        public int Id { get; set; }
        public string LoginAcount { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string Email { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<sbyte> IsAdmin { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Modify { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
