//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Protal.Models
{
    using System;
    using System.Collections.Generic;

    public partial class wz_word
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public Nullable<int> Authority { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public int IsDelete { get; set; }
        public string AuthName
        {
            get
            {
                if (Authority == 0)
                {
                    return "公开";
                }
                if (Authority == 1)
                {
                    return "指定人可见";
                }
                return "仅主人可见";
            }
        }
    }
}
